### ISSUE TITLE
reduced calls to raf.setLength()

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Bytes#119]
We are calling raf.setLength() every time we allocate a new chunk, it is expected that calls to raf.setLength() are rather expensive however this has to be confirmed. ( So may close this issue as wont fix, later )
![image](https://user-images.githubusercontent.com/6506056/82878353-4b146e00-9f33-11ea-950f-08fefb352aea.png)

**Comment by RobAustin** [comment]
its is likely this is related to the following stalls

```
[tree-1/monitor] INFO net.openhft.chronicle.threads.VanillaEventLoop - core-event-loop thread has blocked for 4959 ms.
	at net.openhft.chronicle.bytes.MappedFile.acquireByteStore(MappedFile.java)
	at net.openhft.chronicle.bytes.MappedFile.acquireByteStore(MappedFile.java:311)
	at net.openhft.chronicle.bytes.MappedBytes.acquireNextByteStore0(MappedBytes.java:434)
	at net.openhft.chronicle.bytes.MappedBytes.readPosition(MappedBytes.java:350)
	at net.openhft.chronicle.bytes.MappedBytes.readPosition(MappedBytes.java:53)
	at net.openhft.chronicle.bytes.StreamingDataInput.readWithLength(StreamingDataInput.java:110)
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.bytes(BinaryWire.java:2480)
	at software.chronicle.datagrid.issue.CustomMessage.readMarshallable(CustomMessage.java:43)
	at net.openhft.chronicle.wire.SerializationStrategies$1.readUsing(SerializationStrategies.java:48)
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.marshallable(BinaryWire.java:3321)
	at net.openhft.chronicle.wire.Wires.objectMap(Wires.java:444)
	at net.openhft.chronicle.wire.Wires.object0(Wires.java:505)
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:592)
	at software.chronicle.datagrid.internal.queue.CloseableTailer.next(CloseableTailer.java:65)
	at software.chronicle.datagrid.internal.map.QueueObjectSubscription$TopicSubscriberHandler.guardedSingleAction(QueueObjectSubscription.java:353)
	at software.chronicle.datagrid.internal.map.QueueObjectSubscription$AbstractSubscriberHandler.action(QueueObjectSubscription.java:429)
	at net.openhft.chronicle.threads.VanillaEventLoop.runAllMediumHandler(VanillaEventLoop.java:375)
	at net.openhft.chronicle.threads.VanillaEventLoop.runMediumLoopOnly(VanillaEventLoop.java:291)
	at net.openhft.chronicle.threads.VanillaEventLoop.runLoop(VanillaEventLoop.java:254)
	at net.openhft.chronicle.threads.VanillaEventLoop.run(VanillaEventLoop.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
```

**Comment by RobAustin** [comment]
also, this synchronized (GLOBAL_FILE_LOCK), is locking on a static, in other words, 

```
private static final Object GLOBAL_FILE_LOCK = FileChannel.class;
```

![image](https://user-images.githubusercontent.com/6506056/82879903-8748ce00-9f35-11ea-95ab-2f88018d621e.png)

**Comment by RobAustin** [comment]
@JerryShea these issues can be reproduced by running datagrid, software.chronicle.datagrid.issue.SubscriberThrottlingTest#reproduceTopicSubscriber

**Comment by RobAustin** [comment]
This test above can be improved by setting :

```
builder.strongAppenders(true);
```

**Comment by RobAustin** [comment]
this issue is related to https://github.com/OpenHFT/Chronicle-Bytes/issues/120 which is now fixed so closing this issue.
