### ISSUE TITLE
race condition BackgroundResourceReleaser vs Finalizer?

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Bytes#157]
From customer log
```
2020-12-16 01:31:58.663 [Finalizer] WARN  net.openhft.chronicle.core.io.VanillaReferenceCounted - Discarded without being released
2020-12-16 01:31:58.660 [background~resource~releaser] WARN  net.openhft.chronicle.core.io.BackgroundResourceReleaser - Failed in release/close
net.openhft.chronicle.core.io.ClosedIllegalStateException: Already released
        at net.openhft.chronicle.core.io.VanillaReferenceCounted.callOnRelease(VanillaReferenceCounted.java:97) ~[chronicle-core-2.20.120.jar:?]
        at net.openhft.chronicle.core.io.VanillaReferenceCounted.release(VanillaReferenceCounted.java:88) ~[chronicle-core-2.20.120.jar:?]
        at net.openhft.chronicle.core.io.AbstractReferenceCounted.release(AbstractReferenceCounted.java:123) ~[chronicle-core-2.20.120.jar:?]
        at net.openhft.chronicle.bytes.AbstractBytes.performRelease(AbstractBytes.java:341) ~[chronicle-bytes-2.20.105.jar:2.20.105]
        at net.openhft.chronicle.bytes.MappedBytes.performRelease(MappedBytes.java:535) ~[chronicle-bytes-2.20.105.jar:2.20.105]
        at net.openhft.chronicle.core.io.BackgroundResourceReleaser.performRelease(BackgroundResourceReleaser.java:79) ~[chronicle-core-2.20.120.jar:?]
        at net.openhft.chronicle.core.io.BackgroundResourceReleaser.runReleaseResources(BackgroundResourceReleaser.java:28) ~[chronicle-core-2.20.120.jar:?]
```

Would be good if we could see the type of the referent

**Comment by peter-lawrey** [comment]
In this case, the type its complaining about is MappedBytes.
It would be helpful to enable resource tracing to determine why this happened.

**Comment by peter-lawrey** [comment]
See also https://github.com/OpenHFT/Chronicle-Core/issues/173

**Comment by peter-lawrey** [comment]
I have changed support threads to be more tolerant of releasing resources which have already been released. c.f. `Jvm.supportThread()`
