### ISSUE TITLE
Error when readMarshallable is called on instance with null collection field

### ISSUE THREAD

**Issue by glukos** [OpenHFT/Chronicle-Bytes#196]
S2R:
1. Prepare a BytesMarshallable class where collection field is not initialzed when default constructor is called
2. Create instance of this class, initialize a collection field with non-empty collection
3. Serialize it with writeMarshallable
4. Deserialize it with readMarshallable

Result:
```
java.lang.NullPointerException
	at net.openhft.chronicle.bytes.BytesMarshaller$CollectionFieldAccess.setValue(BytesMarshaller.java:442)
	at net.openhft.chronicle.bytes.BytesMarshaller$FieldAccess.read(BytesMarshaller.java:160)
	at net.openhft.chronicle.bytes.BytesMarshaller.readMarshallable(BytesMarshaller.java:61)
	at net.openhft.chronicle.bytes.BytesUtil.readMarshallable(BytesUtil.java:290)
	at net.openhft.chronicle.bytes.BytesMarshallable.readMarshallable(BytesMarshallable.java:41)
```

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.21ea49](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.21ea49), [BOM-2.21ea134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea134)
