### ISSUE TITLE
BufferedUnderlowException reading a UTF8 message

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#31]
TcpEventHandler -
java.nio.BufferUnderflowException
        at net.openhft.chronicle.bytes.BytesInternal.parseUtf8_SB1(BytesInternal.java:352) ~[chronicle-bytes-1.7.17.jar:?]
        at net.openhft.chronicle.bytes.BytesInternal.parseUtf8(BytesInternal.java:114) ~[chronicle-bytes-1.7.17.jar:?]
        at net.openhft.chronicle.bytes.StreamingDataInput.parseUtf8(StreamingDataInput.java:276) ~[chronicle-bytes-1.7.17.jar:?]
        at net.openhft.chronicle.wire.BinaryWire.getStringBuilder(BinaryWire.java:629) ~[chronicle-wire-1.7.14.jar:?]
        at net.openhft.chronicle.wire.BinaryWire.readText(BinaryWire.java:1071) ~[chronicle-wire-1.7.14.jar:?]

**Comment by peter-lawrey** [comment]
This occurred when trying to skipValue() for padding()

**Comment by peter-lawrey** [comment]
skipValue() had a bug in handling padding when there was nothing after it.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
