### ISSUE TITLE
Improve handling of large Strings.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#35]
The current implementation for BytesInternal fails to write if the String is longer than 1/4 of the block size of a queue.
parseUtf8_SB1 also fails to read Strings of more than 1 MB correctly.

**Comment by RobAustin** [comment]
@peter-lawrey I think the simplest solution is to add a warning if the strings approach ( say 75% ) of the block size ( and suggest they increase the block size ), The only other solution with be to chain 2 or more  excerpts together, however ( although this is the most elegant solution ) I feel its over kill as this has never been reported as an issue and would be very difficult to do correctly, considering queue replication and file-rolling.

**Comment by peter-lawrey** [comment]
We should have a test case which shows what happens when we exceed the safe
window which is block size/4 (the overlap)

For the default settings this is 16 MB.

Note: if this is a real use case we can fix this issue and write sections
of say 1024 characters at a time. This would raise the limit to one billion
bytes per string.
ᐧ

**Comment by dpisklov** [comment]
@peter-lawrey I added tests: `BytesInternalTest#testParseUTF_SB1_LongString` and `BytesInternalTest#testWriteLongString` writing and reading strings of 512Mb and they pass. Has this been fixed already?

**Comment by peter-lawrey** [comment]
I would check all implementations for UTF and 8bit to ensure this is
correct for all of them. (Some are optimised)
ᐧ

**Comment by dpisklov** [comment]
@peter-lawrey I added a handful more tests, using all sorts of UTF8/8bit combinations, and they all pass with 512Mb strings. So shall we assume this is fixed now?

**Comment by peter-lawrey** [comment]
I think so. Certainly more tests help.
ᐧ

**Comment by dpisklov** [comment]
@adhamelia can you provide a test case reproducing it?

**Comment by adhamelia** [comment]
@dpisklov 

PFA log


Usage of map as follows:
 ChronicleMap<String,String> m_monitorAlertsCache =  ChronicleMap
                .of(String.class, String.class)
                .name(TraceOrgSDKConstants.CACHE_MONITOR_ALERTS_CACHE)
                .averageKeySize(100)
                .averageValueSize(1000)
                .entries(1000000L)
                .createPersistedTo(new File(TraceOrgSDKConstants.CURRENT_DIR +TraceOrgSDKConstants.PATH_SEPARATOR+TraceOrgSDKConstants.CACHE_MONITOR_ALERTS_CACHE));
				

We are doing continuous operation of removing particular key or adding new key and iterating map using forEach using different processes following value is being dumped into it just as example

key:"4516|!!|Interface Utilization (%)"
value:"Interface Utilization (%)|@_@|LOOPBACK|!!|32|!!|4|!!|2018-10-9|!!|17:22:25|!!|Interface Utilization (%)|!!|0|!!|LOOPBACK|!!|Interface|!!|2018-10-9 17:22:25|@_@|dc78d0ae-b819-40d2-9295-76f28221e8d7|@_@|0|@_@|Interface Utilization (%) of 192.168.1.242 : LOOPBACK has entered into Clear state with value 0 <br /> *** Correlated Metrics *** <br /> Interface IN Utilization (%) : 0 <br /> Interface OUT Utilization (%) : 0"

After sometime of continuous operation i get below error during iteration as follows and its random:

:6d16c
0006d0e0                                      66 20 74 68              f th
0006d0f0 69 73 20 6e 75 6d 62 65  72 20 69 73 20 6d 6f 72 is numbe r is mor
0006d100 65 20 74 68 61 6e 20 35  30 30 20 62 65 74 77 65 e than 5 00 betwe
0006d110 65 6e 20 74 68 65 20 6d  69 6e 69 6d 75 6d 20 61 en the m inimum a
0006d120 6e 64 20 6d 61 78 69 6d  75 6d 20 6e 75 6d 62 65 nd maxim um numbe
0006d130 72 20 6f 66 20 74 68 72  65 61 64 73 db 86 b6 81 r of thr eads····
0006d140 79 33 31 31 32 7c 21 21  7c 49 6e 74 65 72 66 61 y3112|!! |Interfa
0006d150 63 65 20 55 74 69 6c 69  7a 61 74 69 6f 6e 20 28 ce Utili zation (
0006d160 25 29 7c 21 21 7c 47 69  30 2f 32 30 9a 03 49 6e %)|!!|Gi 0/20··In
0006d170 74 65 72 66 61 63 65 20  55 74 69 6c 69 7a 61 74 terface  Utilizat
0006d180 69 6f 6e 20 28 25 29 7c  40 5f 40 7c 47 69 30 2f ion (%)| @_@|Gi0/
0006d190 32 30 7c 21 21 7c 36 37  7c 21 21 7c 34 7c 21 21 20|!!|67 |!!|4|!!
0006d1a0 7c 32 30 31 38 2d 31 30  2d 39 7c 21 21 7c 34 3a |2018-10 -9|!!|4:
0006d1b0 32 30 3a 32                                      20:2             
... truncated
	at net.openhft.chronicle.bytes.BytesInternal.parseUtf8_SB1(BytesInternal.java:411)
	at net.openhft.chronicle.bytes.BytesInternal.parseUtf8(BytesInternal.java:134)
	at net.openhft.chronicle.bytes.BytesUtil.parseUtf8(BytesUtil.java:151)
	at net.openhft.chronicle.hash.serialization.impl.StringSizedReader.read(StringSizedReader.java:49)
	at net.openhft.chronicle.hash.serialization.impl.StringSizedReader.read(StringSizedReader.java:28)
	at net.openhft.chronicle.map.impl.CompiledMapIterationContext$EntryKeyBytesData.innerGetUsing(CompiledMapIterationContext.java:456)
	at net.openhft.chronicle.map.impl.CompiledMapIterationContext$EntryKeyBytesData.initCachedEntryKey(CompiledMapIterationContext.java:472)
	at net.openhft.chronicle.map.impl.CompiledMapIterationContext$EntryKeyBytesData.cachedEntryKey(CompiledMapIterationContext.java:478)
	at net.openhft.chronicle.map.impl.CompiledMapIterationContext$EntryKeyBytesData.get(CompiledMapIterationContext.java:490)
	at net.openhft.chronicle.map.AbstractChronicleMap.lambda$forEach$1(AbstractChronicleMap.java:80)
	at net.openhft.chronicle.map.AbstractChronicleMap.lambda$forEachEntry$5(AbstractChronicleMap.java:234)
	at net.openhft.chronicle.map.impl.CompiledMapIterationContext.forEachTierEntryWhile(CompiledMapIterationContext.java:3884)
	at net.openhft.chronicle.map.impl.CompiledMapIterationContext.innerForEachSegmentEntryWhile(CompiledMapIterationContext.java:3919)
	at net.openhft.chronicle.map.impl.CompiledMapIterationContext.forEachSegmentEntryWhile(CompiledMapIterationContext.java:3939)
	at net.openhft.chronicle.map.AbstractChronicleMap.forEachEntryWhile(AbstractChronicleMap.java:244)
	at net.openhft.chronicle.map.AbstractChronicleMap.forEachEntry(AbstractChronicleMap.java:233)
	at net.openhft.chronicle.map.AbstractChronicleMap.forEach(AbstractChronicleMap.java:80)

**Comment by dpisklov** [comment]
@adhamelia this doesn't quite help us to reproduce the issue. Are you able to extract the code into a test case that reproduces the error?

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
