### ISSUE TITLE
Bytes.read(byte[]) fails if Bytes constructed with a BytesStore that is a Bytes

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Bytes#426]
At `net.openhft.chronicle.bytes.RandomDataInput#read`, commit #414 has introduced a change which triggers the following exception:

```
Exception in thread "Thread-2" java.lang.ArithmeticException: Unsigned Int 31-bit -28 out of range
	at net.openhft.chronicle.core.Maths.toUInt31(Maths.java:659)
	at net.openhft.chronicle.bytes.RandomDataInput.read(RandomDataInput.java:664)
	at net.openhft.chronicle.bytes.AbstractBytes.read(AbstractBytes.java:1124)
	at net.openhft.chronicle.bytes.StreamingDataInput.read(StreamingDataInput.java:384)
	at net.openhft.chronicle.bytes.VanillaBytes.read(VanillaBytes.java:702)
	at software.chronicle.enterprise.queue.demo.example13.QueueMultiThreadedJLBHBenchmark$Datum.readMarshallable(QueueMultiThreadedJLBHBenchmark.java:133)
```

In this case, 

```
            int len = Math.min(length, Maths.toUInt31(readLimit() - offsetInRDI));
//                                                              0 - 28
```

**Comment by JerryShea** [comment]
What made this happen was some code in a demo that constructed a `Bytes` with a `BytesStore` that is a `Bytes` e.g. `new OnHeapBytes(Bytes.allocateElasticOnHeap(capacity), true)`.

See #427 for some tests that fail if you do this.

Previously in `net.openhft.chronicle.bytes.RandomDataInput#read` there was a cast to `int` which gave a -ve number and the actual read would silently fail. Now we use `Maths.toUInt31` which blows up if you give it a -ve number which arguably is better as it is demonstrating a problem further up the tree (and has enabled us to find this).

**Comment by JerryShea** [comment]
Closed by https://github.com/OpenHFT/Chronicle-Bytes/pull/428
