### ISSUE TITLE
Buffer underflow exception on read8bit call

### ISSUE THREAD

**Issue by maxmorozov** [OpenHFT/Chronicle-Bytes#430]
We have found an issue when use write8bit/read8bit.
The minimal test case is:
```
@Test
public void testReadBytes() {
    Bytes<ByteBuffer> data = Bytes.elascByteBuffer(256);
    data.clear();

    data.write8bit((CharSequence) "d6f4dd20-551e-4825-9f53-4f30d223c0d6");

    data.writeLimit(data.length());

    String id = data.read8bit();
    Assert.assertEquals("d6f4dd20-551e-4825-9f53-4f30d223c0d6", id);
}
```
Excepon trace:
```
net.openh.chronicle.bytes.ul.DecoratedBufferUnderflowExcepon: readCheckOffset0 failed. Offset: 1 + adding: 64 > limit: 37 (given: true)
    at net.openh.chronicle.bytes.AbstractBytes.newBOEReadUpper(AbstractBytes.java:924)
    at net.openh.chronicle.bytes.AbstractBytes.readCheckOffset0(AbstractBytes.java:916)
    at net.openh.chronicle.bytes.AbstractBytes.readCheckOffset(AbstractBytes.java:906)
    at net.openh.chronicle.bytes.AbstractBytes.addressForRead(AbstractBytes.java:1201)
    at net.openh.chronicle.bytes.VanillaBytes.write(VanillaBytes.java:464)
    at net.openh.chronicle.bytes.VanillaBytes.write(VanillaBytes.java:60)
    at net.openh.chronicle.bytes.StreamingDataInput.read8bit(StreamingDataInput.java:357)
    at net.openh.chronicle.bytes.internal.BytesInternal.read8bit(BytesInternal.java:2212)
    at net.openh.chronicle.bytes.StreamingDataInput.read8bit(StreamingDataInput.java:285)
    at ChronicleBytesTest.testReadBytes(ChronicleBytesTest.java:104)
```
The issue was caused by a recently added check in AbstractBytes.addressForRead
```
@Override
public long addressForRead(@NonNegave long offset) throws BufferUnderflowExcepon, IllegalStateExcepon {
    readCheckOffset(offset, isElasc() ? Math.min(64, capacity() - offset) : 0, true);
    return bytesStore.addressForRead(offset);
}
```
It calculates some adding value that is 64 in this case (because the capacity is Long.MAX_VALUE) and checks it against writeLimit that is 37.
It is not clear why this check is needed, but it leads to the issue.
Probably, it should take into account the writeLimit along with the capacity?

**Comment by maxmorozov** [comment]
The issue was fixed in 2.23ea28
