### ISSUE TITLE
Bytes on windows / initializationError / ClassNotFound

### ISSUE THREAD

**Issue by JohannesLichtenberger** [OpenHFT/Chronicle-Bytes#545]
Regarding SirixDB, a user ran a test (which used `Bytes::elasticByteBuffer` somewhere and a class can't be found, which on Windows shouldn't be needed, I guess:

```
java.lang.ExceptionInInitializerError
    at net.openhft.chronicle.bytes.internal.NativeBytesStore.<init>(NativeBytesStore.java:65)
    at net.openhft.chronicle.bytes.internal.NativeBytesStore.<init>(NativeBytesStore.java:83)
    at net.openhft.chronicle.bytes.internal.NativeBytesStore.elasticByteBuffer(NativeBytesStore.java:188)
    at net.openhft.chronicle.bytes.BytesStore.elasticByteBuffer(BytesStore.java:189)
    at net.openhft.chronicle.bytes.Bytes.elasticByteBuffer(Bytes.java:177)
    at net.openhft.chronicle.bytes.Bytes.elasticByteBuffer(Bytes.java:149)
    at io.sirix.io.filechannel.FileChannelWriter.<init>(FileChannelWriter.java:76)
    at io.sirix.io.filechannel.FileChannelStorage.createWriter(FileChannelStorage.java:155)
    at io.sirix.access.trx.node.AbstractResourceSession.createPageTransaction(AbstractResourceSession.java:233)
    at io.sirix.access.trx.node.AbstractResourceSession.beginNodeTrx(AbstractResourceSession.java:442)
    at io.sirix.access.trx.node.AbstractResourceSession.beginNodeTrx(AbstractResourceSession.java:403)
    at io.sirix.access.LocalDatabase.bootstrapResource(LocalDatabase.java:248)
    at io.sirix.access.LocalDatabase.createResource(LocalDatabase.java:218)
    at io.sirix.service.json.shredder.JsonShredderTest.createResource(JsonShredderTest.java:140)
Caused by: java.lang.IllegalStateException: Not found: sun.nio.ch.UnixFileDispatcherImpl
    at net.openhft.chronicle.core.OS.findClass(OS.java:131)
    at net.openhft.chronicle.core.OS.<clinit>(OS.java:100)
    ... 95 more
Caused by: java.lang.ClassNotFoundException: sun.nio.ch.UnixFileDispatcherImpl
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    at net.openhft.chronicle.core.OS.findClass(OS.java:128)
    ... 96 more
```

Currently I have no Windows to check this :-/

**Comment by JerryShea** [comment]
@JohannesLichtenberger all our products are tested on Windows in our CI environment. Maybe the user was running on an [unsupported version](https://github.com/OpenHFT/OpenHFT/blob/ea/docs/Java-Version-Support.adoc)? Unless this can be reproduced e.g. with a unit test, there is not much we can do

**Comment by JohannesLichtenberger** [comment]
```java
            if (Jvm.isJava20Plus()) {
                Class<?> dispatcherClass = findClass("sun.nio.ch.UnixFileDispatcherImpl");
                unmap0 = Jvm.getMethod(dispatcherClass, "unmap0", long.class, long.class);
            } else {
```

This clearly doesn't work on Windows, starting with Java 20, I'd guess...

**Comment by JohannesLichtenberger** [comment]
@JerryShea, it would be awesome if this would be fixed (and Java 21 is along the road, so...).

**Comment by JerryShea** [comment]
@JohannesLichtenberger please review the link in my last comment. We don't support Java 20. You can submit a PR if you like :)

**Comment by JohannesLichtenberger** [comment]
@JerryShea, I can't see the fork button. But as I don't understand why the condition has been added, I'd remove it and put in the code a couple of lines above (for the mapping). I suppose you'll support Java 21, so I could, of course, also wait for the fix...

**Comment by JohannesLichtenberger** [comment]
Not sure, what the proper fix is, but a PR for Chronicle Core: https://github.com/OpenHFT/Chronicle-Core/pull/555
