### ISSUE TITLE
Optimised  the call to Math.round()

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Bytes#70]
It was shown to added latency 

```
204	at java.lang.Double.doubleToRawLongBits(Native Method)
	at java.lang.Math.round(Math.java:717)
	at net.openhft.chronicle.bytes.ByteStringAppender.append(ByteStringAppender.java:176)
	at software.chronicle.fix44min.generators.MessageGenerator.orderQty(MessageGenerator.java:199)
	at software.chronicle.fix44min.messages.NewOrderSingle.copyTo(NewOrderSingle.java:128)
	at software.chronicle.fix44min.messages.NewOrderSingle.copyTo(NewOrderSingle.java:113)
	at software.chronicle.fix.staticcode.VanillaSessionHandler.copyToMG(VanillaSessionHandler.java:598)
	at software.chronicle.fix.staticcode.VanillaSessionHandler.sendMessage(VanillaSessionHandler.java:502)
```

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
